// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axqmjievytyewusbmyrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cW1qaWV2eXR5ZXd1c2JteXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTM4ODAsImV4cCI6MjA2NDgyOTg4MH0.nzkYG_IK5sRW7leRc14OboZlwlK97CwDhhlmuKxJi-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);